### ISSUE TITLE
Compatibility issue with nim 0.17.0

### ISSUE THREAD

**Issue by yuliyv** [euantorano/dotenv.nim#1]
When attempting to utilize this package with the latest nim version (0.17.0) I was getting the following error while running the test suite:

```
$ nim c -r tests/main.nim 
/Users/yuliy/code/dotenv.nim/dotenv.nim(40, 38) template/generic instantiation from here
lib/system.nim(2656, 7) Error: can raise an unlisted exception: ref AssertionError
```

Which I believe stems from the addition of a `doAssert` in the core os module (found [here](https://github.com/nim-lang/Nim/blob/devel/lib/pure/os.nim#L346)).  

I believe that [this change in my fork](https://github.com/euantorano/dotenv.nim/compare/master...yuliyv:patch-0.17-compatibility?expand=1) should resolve the issue and maintain backwards compatibility with previous versions, but I am fairly new to nim so any feedback is appreciated!

**Comment by euantorano** [comment]
Thanks for the report, I can't seem to replicate the issue with either Nim 0.17.0 or $HEAD on my machine, which is odd...

**Comment by euantorano** [comment]
I cannot replicate this locally, but have pushed an updated version with some changes to directory structure and with documentation included. I've also asked on IRC to see if it's some quirk in my setup that prevents that exception from being thrown.

**Comment by euantorano** [comment]
Araq pointed me in the right direction - that exception won't be raised on Windows which explains why I'm not seeing it on this machine!

**Comment by yuliyv** [comment]
Thanks for your help on this!
