### ISSUE TITLE
Support file paths without quoting them

### ISSUE THREAD

**Issue by ajusa** [euantorano/dotenv.nim#3]
Hey @euantorano, I saw your message. Here's a minimal example of what I expect to work:

```nim
import dotenv

loadEnvFromString("""
FS_ROOT=/home/ajusa/Documents
""")
```
```
Error: unhandled exception: (1, 29) Error: symbol expected, but found: /Documents [DotEnvParseError]
```
If I put the path in quotes, it works as expected (and that's what I'm doing for now). File paths shouldn't require quotes though I would think, since bash doesn't need them either.

**Comment by euantorano** [comment]
Awesome, thanks for getting back to me. 

I’ll have a look at this today or tomorrow and see what I can do.

**Comment by euantorano** [comment]
Sorry for the delay, after starting to look I decided to take a different approach and simplify the code a bunch. This should make it a little easier to maintain in the future too, which is nice.

The code is in another branch while I overhaul some stuff and get CI running through GitHub actions. It will be released with a new major version number as the API is changing a bit too to simplify things even further, but you can check it out here: https://github.com/euantorano/dotenv.nim/tree/fix/3-directory-paths
